import { useLoaderData } from "react-router";
import PairedAgentTools from "../components/paired-agent-tools";
import AgentBrief from "../components/agent-brief";
import { Card, WorkspacePage } from "../components/workspace-page";
import { getPairedAgent } from "../services/agent-pairing.server";
import { getMerchantAnalysis } from "../services/merchant-analysis.server";
import prisma from "../db.server";
import { unauthenticated } from "../shopify.server";

export async function loader({ request }) {
  const pairing = await getPairedAgent(request);
  if (!pairing) {
    return { pairing: null };
  }

  const { admin } = await unauthenticated.admin(pairing.shop);
  const [analysis, activity] = await Promise.all([
    getMerchantAnalysis(admin, 30),
    prisma.activityEntry.findMany({
      where: { shop: pairing.shop },
      orderBy: { createdAt: "desc" },
      take: 12,
    }),
  ]);
  return { pairing, analysis, activity };
}

export default function PairedAgentPage() {
  const data = useLoaderData();

  if (!data.pairing) {
    return (
      <main className="workspace-page">
        <p className="workspace-eyebrow">MerchRelay external agent</p>
        <h1>Pair with a merchant first</h1>
        <div className="workspace-callout">
          Use the one-time pairing link generated by the merchant from the
          Shopify Admin workspace.
        </div>
      </main>
    );
  }

  return (
    <WorkspacePage
      eyebrow="Paired external agent"
      title="MerchRelay agent workspace"
      description={`Connected to ${data.pairing.shop}. Merchant approval remains required before every Shopify change.`}
    >
      <PairedAgentTools />
      <Card title="Pairing authority" detail="Expires automatically">
        <div className="workspace-callout">
          This session can read merchant data, research public catalog results,
          create pending proposals, and apply only exact merchant-approved
          revisions. It cannot approve, reject, revise, cancel, or create a new
          pairing.
        </div>
      </Card>
      <AgentBrief analysis={data.analysis} activity={data.activity} />
    </WorkspacePage>
  );
}
